const PRODUCTS=[
{id:'burger',name:'Smoky Savanna Burger',category:'Mains',price:850,image:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85',desc:'Char-grilled beef, smoky sauce, crisp lettuce and house pickles.',options:[{name:'Fries',type:'radio',required:true,choices:[['none','No fries',0],['regular','Add regular fries',150],['loaded','Loaded fries',250]]},{name:'Drink',type:'radio',required:true,choices:[['none','No drink',0],['soda','Soda',100],['juice','Fresh juice',180]]}]},
{id:'chicken',name:'Peri-Peri Chicken',category:'Mains',price:1100,image:'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=900&q=85',desc:'Flame-grilled chicken with our signature peri-peri glaze.',options:[{name:'Heat level',type:'radio',required:true,choices:[['mild','Mild',0],['medium','Medium',0],['hot','Hot',0]]},{name:'Side',type:'radio',required:true,choices:[['chips','Seasoned chips',200],['rice','Coconut rice',180],['salad','Garden salad',150]]}]},
{id:'pizza',name:'Garden Fire Pizza',category:'Mains',price:1250,image:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=85',desc:'Mozzarella, roasted peppers, mushrooms, herbs and chili oil.',options:[{name:'Size',type:'radio',required:true,choices:[['medium','Medium',0],['large','Large +350',350]]}]},
{id:'fries',name:'Loaded Savanna Fries',category:'Sides',price:450,image:'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=85',desc:'Crispy fries topped with house sauce and herbs.',options:[{name:'Extra sauce',type:'radio',required:true,choices:[['no','No extra sauce',0],['yes','Add extra sauce',80]]}]},
{id:'juice',name:'Fresh Passion Juice',category:'Drinks',price:280,image:'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=900&q=85',desc:'Fresh passion fruit juice served chilled.',options:[{name:'Ice',type:'radio',required:true,choices:[['normal','Normal ice',0],['less','Less ice',0],['none','No ice',0]]}]},
{id:'cake',name:'Chocolate Fudge Cake',category:'Desserts',price:500,image:'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=85',desc:'Rich chocolate cake with a smooth fudge finish.',options:[]}
];
const money=n=>'KSh '+Number(n).toLocaleString();
function getCart(){return JSON.parse(localStorage.getItem('doe_cart')||'[]')}
function saveCart(c){localStorage.setItem('doe_cart',JSON.stringify(c));updateCount()}
function updateCount(){const n=getCart().reduce((s,i)=>s+i.qty,0);document.querySelectorAll('#cart-count').forEach(x=>x.textContent=n)}
function product(id){return PRODUCTS.find(p=>p.id===id)}
function addItem(item){const c=getCart();const key=JSON.stringify(item.options||{});const existing=c.find(x=>x.id===item.id&&JSON.stringify(x.options||{})===key);if(existing)existing.qty+=item.qty;else c.push(item);saveCart(c);window.location.href='checkout.html'}
function renderMenu(){const grid=document.getElementById('menu-grid');if(!grid)return;grid.innerHTML=PRODUCTS.map(p=>`<article class="menu-card"><img src="${p.image}" alt="${p.name}"><div class="menu-card-body"><p class="eyebrow">${p.category}</p><h3>${p.name}</h3><p>${p.desc}</p><div class="price-row"><span class="price">${money(p.price)}</span><a class="add-btn" href="product.html?id=${p.id}">Customize →</a></div></div></article>`).join('')}
function renderProduct(){const el=document.getElementById('product-view');if(!el)return;const id=new URLSearchParams(location.search).get('id')||'burger';const p=product(id);if(!p){el.innerHTML='<div class="empty">Product not found.</div>';return}el.innerHTML=`<div class="product-layout"><img src="${p.image}" alt="${p.name}"><div class="product-info"><p class="eyebrow">${p.category}</p><h1>${p.name}</h1><p class="desc">${p.desc}</p><h2>${money(p.price)}</h2><form id="product-form">${p.options.map((o,i)=>`<div class="option-group"><h4>${o.name}</h4>${o.choices.map((c,j)=>`<label><input type="radio" name="option${i}" value="${c[0]}" data-price="${c[2]}" ${j===0?'checked':''}> ${c[1]} ${c[2]?'— '+money(c[2]):''}</label>`).join('')}</div>`).join('')}<div class="qty"><label for="qty">Quantity</label><input id="qty" type="number" min="1" value="1"></div><button class="btn wide" type="submit">Add to order</button></form></div></div>`;document.getElementById('product-form').onsubmit=e=>{e.preventDefault();const opts={};let extra=0;p.options.forEach((o,i)=>{const x=document.querySelector(`input[name=option${i}]:checked`);if(x){opts[o.name]=x.value;extra+=Number(x.dataset.price)}});addItem({id:p.id,name:p.name,base:p.price,unit:p.price+extra,qty:Math.max(1,Number(document.getElementById('qty').value)||1),options:opts,image:p.image})}}
function renderCheckout(){const el=document.getElementById('checkout-view');if(!el)return;const c=getCart();if(!c.length){el.innerHTML='<div class="empty"><h2>Your cart is empty.</h2><p>Add a product from the menu or a direct Order button.</p><a class="btn" href="menu.html">Browse menu</a></div>';return}const subtotal=c.reduce((s,i)=>s+i.unit*i.qty,0);el.innerHTML=`<div class="checkout-layout"><section><p class="eyebrow">CHECKOUT</p><h1>Complete your order.</h1><div class="panel"><h2>Your items</h2>${c.map((i,n)=>`<div class="summary-row"><span>${i.qty} × ${i.name}<small style="display:block">${Object.entries(i.options||{}).map(x=>x[0]+': '+x[1]).join(' • ')}</small></span><strong>${money(i.unit*i.qty)}</strong></div>`).join('')}<div class="summary-row total"><span>Total</span><span>${money(subtotal)}</span></div></div></section><section class="panel"><h2>Customer details</h2><form id="checkout-form"><div class="field"><label>Name</label><input id="customer" required placeholder="Your name"></div><div class="field"><label>Phone</label><input id="phone" required placeholder="07xx xxx xxx"></div><div class="field"><label>Delivery / pickup note</label><input id="note" placeholder="e.g. Westlands, apartment 4B"></div><div class="option-group payment"><h4>Payment method</h4><label><input type="radio" name="payment" value="M-Pesa" checked> M-Pesa</label><label><input type="radio" name="payment" value="Card"> Card</label><label><input type="radio" name="payment" value="PayPal"> PayPal</label></div><button class="btn wide">Pay ${money(subtotal)} (demo)</button></form></section></div>`;document.getElementById('checkout-form').onsubmit=e=>{e.preventDefault();const order={id:'SB-'+Date.now().toString().slice(-6),customer:document.getElementById('customer').value,phone:document.getElementById('phone').value,note:document.getElementById('note').value,payment:document.querySelector('input[name=payment]:checked').value,items:c,total:subtotal,status:'New',created:new Date().toISOString()};const orders=JSON.parse(localStorage.getItem('doe_orders')||'[]');orders.unshift(order);localStorage.setItem('doe_orders',JSON.stringify(orders));localStorage.removeItem('doe_cart');location.href='dashboard.html?new='+order.id}}
function renderDashboard(){const el=document.getElementById('dashboard-view');if(!el)return;let orders=JSON.parse(localStorage.getItem('doe_orders')||'[]');const statuses=['New','Preparing','Ready','Completed'];el.innerHTML=`<div class="dashboard-head"><div><p class="eyebrow">SAVANNA BITES • RESTAURANT</p><h1>Incoming orders.</h1></div><a class="btn" href="menu.html">Open customer menu</a></div><div class="orders">${orders.length?orders.map(o=>`<article class="order-card"><div><h3>${o.id} · ${o.customer}</h3><p>${o.phone} · ${o.payment}</p><p>${o.items.map(i=>`${i.qty}× ${i.name}`).join(', ')}</p><p>${o.note||'No delivery note'}</p></div><div><div class="order-status">${o.status}</div><strong>${money(o.total)}</strong><div class="status-actions">${statuses.map(s=>`<button onclick="setStatus('${o.id}','${s}')">${s}</button>`).join('')}</div></div></article>`).join(''):'<div class="empty"><h2>No orders yet.</h2><p>Open the menu and place a demo order to see it arrive here.</p></div>'}</div>`}
function setStatus(id,status){const orders=JSON.parse(localStorage.getItem('doe_orders')||'[]');const o=orders.find(x=>x.id===id);if(o)o.status=status;localStorage.setItem('doe_orders',JSON.stringify(orders));renderDashboard()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-order-product]');if(b){e.preventDefault();location.href='product.html?id='+encodeURIComponent(b.dataset.orderProduct)}});updateCount();renderMenu();renderProduct();renderCheckout();renderDashboard();
