function escapeCheckoutHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function checkoutItemOptions(item){return Object.entries(item.options||{}).map(x=>escapeCheckoutHtml(x[0])+': '+escapeCheckoutHtml(x[1])).join(' • ')||'Standard item';}
function checkoutPaymentCard(value,icon,title,description,disabled=false,badge=''){
  return '<label class="checkout-payment"><input type="radio" name="payment" value="'+escapeCheckoutHtml(value)+'" '+(value==='M-Pesa'?'checked ':'')+(disabled?'disabled':'')+'><span class="checkout-payment-card"><span class="checkout-payment-icon">'+icon+'</span><span class="checkout-payment-copy"><strong>'+title+'</strong><small>'+description+'</small></span><span class="checkout-payment-check">✓</span></span>'+(badge?'<span class="checkout-payment-badge">'+badge+'</span>':'')+'</label>';
}
async function renderCheckoutUpgrade(){
  const el=document.getElementById('checkout-view');if(!el)return;
  const c=getCart();
  if(!c.length){el.innerHTML='<div class="checkout-empty"><h2>Your cart is empty.</h2><p>Choose something from the menu and we will take it from there.</p><a class="btn" href="menu.html">Browse the menu</a></div>';return;}
  const subtotal=c.reduce((sum,i)=>sum+i.unit*i.qty,0);
  let business={pickup_address:'Savanna Bites, Nairobi, Kenya'};try{business=await apiRequest('/api/businesses/'+encodeURIComponent(BUSINESS_ID));}catch{}
  el.innerHTML='<div class="checkout-shell">'+
    '<section class="checkout-hero"><div><p class="checkout-kicker">CHECKOUT</p><h1>Almost yours.</h1><p>Review your order, tell us where to bring it and choose your payment method. Nothing is charged until you continue.</p></div><div class="checkout-trust-chip"><b>✓</b> Secure &amp; protected</div></section>'+
    '<div class="checkout-progress" aria-label="Checkout progress"><div class="checkout-progress-item active"><span class="checkout-progress-dot">1</span><span>Your details</span></div><div class="checkout-progress-item active"><span class="checkout-progress-dot">2</span><span>Delivery</span></div><div class="checkout-progress-item active"><span class="checkout-progress-dot">3</span><span>Payment</span></div></div>'+
    '<div class="checkout-columns"><div class="checkout-main">'+
      '<section class="checkout-card"><div class="checkout-card-head"><div><p class="checkout-kicker">01 · CONTACT</p><h2>Who are we delivering to?</h2><p>We only use these details to process and update your order.</p></div><span class="checkout-step">01</span></div><form id="checkout-upgrade"><div class="checkout-fields"><div class="checkout-field"><label for="customer">Full name</label><input id="customer" required autocomplete="name" placeholder="Your name"></div><div class="checkout-field"><label for="phone">Phone number</label><input id="phone" required autocomplete="tel" inputmode="tel" placeholder="07xx xxx xxx"></div><div class="checkout-field full"><label for="email">Email address</label><input id="email" type="email" required autocomplete="email" placeholder="you@example.com"><small class="checkout-field-help">Used for your order and payment updates.</small></div></div></section>'+
      '<section class="checkout-card"><div class="checkout-card-head"><div><p class="checkout-kicker">02 · DELIVERY</p><h2>Where should it go?</h2><p>Enter a clear location so the delivery fee can be calculated accurately.</p></div><span class="checkout-step">02</span></div><div class="checkout-fields"><div class="checkout-field full"><label for="delivery-address">Delivery location</label><div class="checkout-location-row"><input id="delivery-address" required autocomplete="street-address" placeholder="Estate, building, street or landmark"><button class="checkout-location-btn" type="button" id="location-button">USE MY LOCATION</button></div><small id="location-status" class="checkout-field-help">You can type the address instead if you prefer not to share device location.</small></div><div class="checkout-field full"><label for="note">Delivery note <span style="font-weight:500;color:var(--checkout-muted)">(optional)</span></label><input id="note" autocomplete="off" placeholder="Gate, floor, landmark or special instruction"></div></div><div id="checkout-quote" class="checkout-quote" hidden><div><strong>Delivery fee ready</strong><small id="route-summary">Route details will appear here.</small></div><strong id="delivery-fee">KSh 0</strong></div></section>'+
      '<section class="checkout-card"><div class="checkout-card-head"><div><p class="checkout-kicker">03 · PAYMENT</p><h2>How would you like to pay?</h2><p>Choose a method. You will be taken through the secure payment step next.</p></div><span class="checkout-step">03</span></div><div class="checkout-payment-grid">'+checkoutPaymentCard('M-Pesa','M','M-Pesa','Pay securely from your phone')+checkoutPaymentCard('Card','▣','Card','Visa, Mastercard and more')+checkoutPaymentCard('PayPal','P','PayPal','Pay with your PayPal account',true,'SOON')+'</div><div class="checkout-paypal-note">PayPal is displayed as a future payment option. It stays disabled until the restaurant has a live PayPal merchant connection and the server-side payment flow is ready.</div><div class="checkout-legal"><label class="checkout-check"><input id="terms-accepted" type="checkbox" required><span>I agree to the <a href="terms.html?businessId='+encodeURIComponent(BUSINESS_ID)+'" target="_blank" rel="noopener">Terms &amp; Conditions</a> and acknowledge the <a href="privacy.html?businessId='+encodeURIComponent(BUSINESS_ID)+'" target="_blank" rel="noopener">Privacy Notice</a>.</span></label><label class="checkout-check"><input id="marketing-opt-in" type="checkbox"><span>Send me optional restaurant offers and updates by SMS/email.</span></label></div><div class="checkout-actions"><button class="checkout-primary" id="quote-button" type="button">CALCULATE DELIVERY FEE</button><button class="checkout-primary" id="pay-button" type="submit" disabled>CONTINUE TO SECURE PAYMENT</button></div><p id="checkout-error" class="checkout-error muted" aria-live="polite"></p></form></section>'+
    '</div><aside class="checkout-summary"><section class="checkout-card checkout-summary-card"><div class="checkout-summary-top"><p class="checkout-summary-label">YOUR ORDER</p><div class="checkout-summary-title"><h2>Order summary</h2><a href="menu.html">Edit</a></div></div><div class="checkout-items">'+c.map(i=>'<article class="checkout-item"><div class="checkout-item-thumb">'+(i.image?'<img src="'+escapeCheckoutHtml(i.image)+'" alt="">':'')+'</div><div class="checkout-item-copy"><strong>'+escapeCheckoutHtml(i.name)+'</strong><small>'+i.qty+' × '+checkoutItemOptions(i)+'</small></div><span class="checkout-item-price">'+money(i.unit*i.qty)+'</span></article>').join('')+'</div><div class="checkout-totals"><div class="checkout-total-row"><span>Subtotal</span><strong>'+money(subtotal)+'</strong></div><div class="checkout-total-row"><span>Delivery</span><strong id="summary-delivery">Calculate next</strong></div><div class="checkout-total-row final"><span>Total</span><strong id="checkout-total">'+money(subtotal)+'</strong></div></div><div class="checkout-route" id="summary-route">Your delivery fee will appear here after the route is calculated.</div><div class="checkout-trust"><div><b>✓</b>Secure</div><div><b>↻</b>Trackable</div><div><b>⌁</b>Protected</div></div></section></aside></div></div>';
  const form=document.getElementById('checkout-upgrade');let quote=null,customerLat=null,customerLng=null;
  const quoteButton=document.getElementById('quote-button'),locationButton=document.getElementById('location-button'),locationStatus=document.getElementById('location-status'),payButton=document.getElementById('pay-button'),error=document.getElementById('checkout-error');
  locationButton.addEventListener('click',()=>{if(!navigator.geolocation){locationStatus.textContent='Location is not available in this browser.';return;}locationButton.disabled=true;locationButton.textContent='LOCATING…';navigator.geolocation.getCurrentPosition(p=>{customerLat=p.coords.latitude;customerLng=p.coords.longitude;locationStatus.textContent='Location captured. You can now calculate the delivery fee.';locationButton.textContent='LOCATION CAPTURED ✓';locationButton.disabled=false;},()=>{locationStatus.textContent='Location permission was not granted. Enter the delivery address manually.';locationButton.textContent='USE MY LOCATION';locationButton.disabled=false;},{enableHighAccuracy:true,timeout:10000,maximumAge:60000});});
  quoteButton.addEventListener('click',async()=>{const address=document.getElementById('delivery-address').value.trim();if(!address){error.textContent='Enter your delivery location first.';document.getElementById('delivery-address').focus();return;}quoteButton.disabled=true;quoteButton.innerHTML='<span class="checkout-spinner"></span> CALCULATING…';error.textContent='';try{quote=await getDeliveryQuote({pickupAddress:business.pickup_address||'Savanna Bites, Nairobi, Kenya',deliveryAddress:address,latitude:customerLat,longitude:customerLng});let zone=null;if(customerLat!==null&&customerLng!==null){try{zone=await apiRequest('/api/delivery/zones/quote',{method:'POST',body:JSON.stringify({businessId:BUSINESS_ID,latitude:customerLat,longitude:customerLng,orderAmount:subtotal})});}catch{}}if(zone)quote={...quote,deliveryFee:zone.deliveryFee,zoneName:zone.zoneName};const fee=Number(quote.deliveryFee||0),total=subtotal+fee;document.getElementById('delivery-fee').textContent=money(fee);document.getElementById('summary-delivery').textContent=money(fee);document.getElementById('checkout-total').textContent=money(total);const routeText=Number(quote.km).toFixed(1)+' km · about '+Math.max(1,Math.round(Number(quote.minutes)))+' min · '+(quote.branchName||'Best available branch')+' · '+(quote.pricingMode==='AUTO'?'automatic platform pricing':'restaurant pricing rules');document.getElementById('route-summary').textContent=routeText;document.getElementById('summary-route').textContent=routeText;document.getElementById('checkout-quote').hidden=false;payButton.disabled=false;error.textContent='Delivery fee locked into this order quote.';}catch(err){quote=null;payButton.disabled=true;error.textContent=err.message||'Could not calculate delivery fee.';}finally{quoteButton.disabled=false;quoteButton.textContent='RECALCULATE DELIVERY FEE';}});
  form.addEventListener('submit',async e=>{e.preventDefault();if(!quote){error.textContent='Calculate the delivery fee before paying.';return;}if(!document.getElementById('terms-accepted').checked){error.textContent='Please accept the Terms & Conditions to continue.';return;}const payment=document.querySelector('input[name=payment]:checked')?.value||'M-Pesa';if(payment==='PayPal'){error.textContent='PayPal is not enabled for this restaurant yet.';return;}payButton.disabled=true;quoteButton.disabled=true;payButton.innerHTML='<span class="checkout-spinner"></span> CREATING SECURE PAYMENT…';error.textContent='';try{const order=await createRemoteOrder({customer:document.getElementById('customer').value.trim(),phone:document.getElementById('phone').value.trim(),email:document.getElementById('email').value.trim(),note:document.getElementById('note').value.trim(),deliveryAddress:document.getElementById('delivery-address').value.trim(),payment,items:c,subtotal,total:subtotal+Number(quote.deliveryFee),quoteId:quote.quoteId,legal:{termsAccepted:true,privacyNoticeAccepted:true,marketingOptIn:document.getElementById('marketing-opt-in').checked}});write('doe_last_order',order.id);setCustomerOrderToken(order.customerAccessToken);const paymentResult=await initializePaystackPayment(order.id);if(paymentResult.mode==='redirect'&&paymentResult.authorizationUrl){localStorage.removeItem('doe_cart');location.href=paymentResult.authorizationUrl;return;}if(paymentResult.mode==='mobile_money'){localStorage.setItem('doe_last_payment_reference',paymentResult.reference);localStorage.removeItem('doe_cart');location.href='order.html?id='+encodeURIComponent(order.id)+'&payment=pending';return;}throw new Error('Payment could not be started');}catch(err){payButton.disabled=false;quoteButton.disabled=false;payButton.textContent='CONTINUE TO SECURE PAYMENT';error.textContent=err.message||'We could not start the payment.';console.error(err);}});
}
renderCheckoutUpgrade();