const app=document.getElementById('app');
const logout=document.getElementById('logout');
let businesses=[],selected=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2000)}
function login(){
app.innerHTML=`<section class="login"><span class="eyebrow">PLATFORM OWNER</span><h1>Control Centre.</h1><p class="muted">Master control for restaurants, packages, website connections and delivery mode.</p><form id="loginForm"><div class="field"><label>ADMIN EMAIL</label><input id="email" type="email" required></div><div class="field"><label>PASSWORD</label><input id="password" type="password" required></div><button class="btn wide">SIGN IN</button><div id="loginError"></div></form></section>`;
document.getElementById('loginForm').onsubmit=async e=>{
e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;b.textContent='SIGNING IN…';
try{const d=await controlApi('/api/control/login',{method:'POST',body:JSON.stringify({email:email.value,password:password.value})});setControlToken(d.token);await boot()}
catch(x){document.getElementById('loginError').innerHTML='<div class="error">'+esc(x.message)+'</div>'}
finally{b.disabled=false;b.textContent='SIGN IN'}};
}
async function boot(){try{await controlApi('/api/control/me');logout.classList.remove('hidden');logout.onclick=async()=>{try{await controlApi('/api/control/logout',{method:'POST'})}catch{}setControlToken('');location.reload()};await loadBusinesses()}catch{setControlToken('');login()}}
async function loadBusinesses(){const d=await controlApi('/api/control/businesses');businesses=d.businesses||[];renderHome()}
function renderHome(){
const list=businesses.map(b=>`<article class="business" onclick="openBusiness('${b.id}')"><div class="business-top"><div><b>${esc(b.name)}</b><small>${esc(b.slug)} · ${b.package_type==='ADVANCED'?'ADVANCED DELIVERY':'DIGITAL ORDERING'}</small></div><span class="pill ${b.rider_connected?'':'off'}">${b.rider_connected?'3 DASHBOARDS':'2 DASHBOARDS'}</span></div><small>Customer ${b.customer_connected?'connected':'not connected'} · Rider ${b.rider_connected?'connected':'not connected'}</small></article>`).join('');
app.innerHTML=`<section class="hero"><div><span class="eyebrow">MASTER PLATFORM CONTROL</span><h1>Control Centre.</h1><p class="muted">One control panel for every restaurant tenant.</p></div><button class="btn" onclick="newBusiness()">＋ NEW RESTAURANT</button></section><section class="stats"><article class="stat"><span>RESTAURANTS</span><strong>${businesses.length}</strong></article><article class="stat"><span>DIGITAL ORDERING</span><strong>${businesses.filter(b=>b.package_type!=='ADVANCED').length}</strong></article><article class="stat"><span>ADVANCED</span><strong>${businesses.filter(b=>b.package_type==='ADVANCED').length}</strong></article><article class="stat"><span>RIDER CONNECTED</span><strong>${businesses.filter(b=>b.rider_connected).length}</strong></article></section><div class="grid"><section class="panel"><span class="eyebrow">TENANTS</span><h2>Restaurant systems</h2>${list||'<p class="muted">No restaurants yet.</p>'}</section><section class="panel"><span class="eyebrow">SYSTEM MODEL</span><h2>Three dashboards</h2><div class="notice"><b>Customer</b><br>Menu + checkout + order tracking.</div><div class="notice"><b>Restaurant</b><br>Orders, menu, branches, payments and operations.</div><div class="notice"><b>Rider</b><br>Enabled only when Advanced Delivery is connected.</div><p class="muted">A public website URL can be stored as the restaurant's homepage. A URL alone cannot grant permission to rewrite files on another host.</p></section></div>`;
}
function newBusiness(){selected=null;app.innerHTML=formHtml({name:'',slug:'',package_type:'DIGITAL_ORDERING',mpesa_phone:'',website_url:'',customer_connected:true,rider_connected:false},true)}
function openBusiness(id){selected=businesses.find(x=>x.id===id);if(selected)app.innerHTML=formHtml(selected,false)}
function formHtml(b,isNew){
const base=location.origin+location.pathname.replace('control.html','');
const customer=base+'menu.html?businessId='+encodeURIComponent(b.id||'BUSINESS_ID');
const manager=base+'manager.html?businessId='+encodeURIComponent(b.id||'BUSINESS_ID');
const rider=base+'rider.html?businessId='+encodeURIComponent(b.id||'BUSINESS_ID');
const connector=base+'restaurant-connector.js';
let services=isNew?'':`<section class="panel section"><span class="eyebrow">GENERATED SERVICES</span><h2>Dashboard endpoints</h2><div class="connection"><div><b>CUSTOMER MENU / CHECKOUT</b><div class="url">${esc(customer)}</div><button class="btn copy" onclick="copyText('${customer}')">COPY</button></div><div><b>RESTAURANT MANAGER</b><div class="url">${esc(manager)}</div><button class="btn copy" onclick="copyText('${manager}')">COPY</button></div><div><b>RIDER DASHBOARD</b><div class="url">${esc(rider)}</div><button class="btn copy" onclick="copyText('${rider}')">COPY</button></div></div><div class="section"><span class="eyebrow">WEBSITE CONNECTOR</span><h2>Connect Menu / Order Now</h2><p class="muted">Add this once to the restaurant homepage and mark its menu/order links with data-restaurant-menu or data-restaurant-order.</p><div class="code">&lt;script src="${esc(connector)}" data-business-id="${esc(b.id)}"&gt;&lt;/script&gt;</div><button class="btn copy" onclick="copyText(this.previousElementSibling.textContent)">COPY CONNECTOR</button><div class="notice"><b>Important:</b> public URL = address, not write permission. Direct automatic editing of GitHub, Namecheap, Cloudflare or another host requires authenticated access to that host.</div></div></section>`;
return `<section class="hero"><div><span class="eyebrow">${isNew?'NEW TENANT':'TENANT CONTROL'}</span><h1>${isNew?'Create.':'Configure.'}</h1></div><button class="ghost" onclick="renderHome()">← BACK</button></section><section class="panel"><form id="businessForm"><div class="connection"><div class="field"><label>RESTAURANT NAME</label><input id="name" required value="${esc(b.name)}"></div><div class="field"><label>SLUG</label><input id="slug" required value="${esc(b.slug)}"></div></div><div class="connection"><div class="field"><label>PACKAGE</label><select id="package"><option value="DIGITAL_ORDERING" ${b.package_type==='DIGITAL_ORDERING'?'selected':''}>DIGITAL ORDERING — CUSTOMER + MANAGER</option><option value="ADVANCED" ${b.package_type==='ADVANCED'?'selected':''}>ADVANCED — CUSTOMER + MANAGER + RIDER</option></select></div><div class="field"><label>RESTAURANT M-PESA / SETTLEMENT PHONE</label><input id="mpesa" value="${esc(b.mpesa_phone||'')}" placeholder="07xx xxx xxx"></div><div class="field"><label>PAYSTACK SUBACCOUNT CODE <small>(OPTIONAL)</small></label><input id="paystackSubaccount" value="${esc(b.paystack_subaccount_code||'')}" placeholder="ACCT_..."></div></div><div class="section"><span class="eyebrow">WEBSITE CONNECTION</span><div class="field"><label>RESTAURANT HOMEPAGE URL</label><input id="website" type="url" value="${esc(b.website_url||'')}" placeholder="https://restaurant.com"></div><div class="switch"><span><b>CONNECT CUSTOMER DASHBOARD</b><br><small class="muted">Menu and checkout become the ordering destination.</small></span><input id="customerConnected" type="checkbox" ${b.customer_connected?'checked':''}></div><div class="switch"><span><b>CONNECT RIDER DASHBOARD</b><br><small class="muted">Enables automatic delivery and rider operations.</small></span><input id="riderConnected" type="checkbox" ${b.rider_connected?'checked':''}></div><button class="btn wide">SAVE SYSTEM</button></form><div id="formError"></div></section>${services}<section class="panel section"><span class="eyebrow">PAYMENT ROUTING</span><h2>Restaurant settlement</h2><p class="muted">The M-Pesa number is stored as restaurant settlement information. Actual movement of customer funds is controlled by the configured payment-provider account/subaccount; entering a phone number alone cannot redirect money.</p></section>`;
}
function copyText(v){navigator.clipboard?.writeText(v).then(()=>toast('Copied')).catch(()=>{const t=document.createElement('textarea');t.value=v;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove();toast('Copied')})}
async function submitBusiness(e){e.preventDefault();const b=e.target.querySelector('button'),body={name:name.value.trim(),slug:slug.value.trim(),packageType:package.value,mpesaPhone:mpesa.value.trim(),paystackSubaccountCode:paystackSubaccount.value.trim(),websiteUrl:website.value.trim(),customerConnected:customerConnected.checked,riderConnected:riderConnected.checked};b.disabled=true;b.textContent='SAVING…';try{const d=selected?await controlApi('/api/control/businesses/'+selected.id,{method:'PATCH',body:JSON.stringify(body)}):await controlApi('/api/control/businesses',{method:'POST',body:JSON.stringify(body)});toast('System saved');await loadBusinesses();openBusiness(d.business.id)}catch(x){document.getElementById('formError').innerHTML='<div class="error">'+esc(x.message)+'</div>'}finally{b.disabled=false;b.textContent='SAVE SYSTEM'}}
document.addEventListener('submit',e=>{if(e.target.id==='businessForm')submitBusiness(e)});
if(controlToken())boot();else login();