(function(){
'use strict';
const store=new Map();let overlay=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES',maximumFractionDigits:0}).format(Number(v||0));
const date=v=>v?new Date(v).toLocaleString('en-KE',{dateStyle:'medium',timeStyle:'short'}):'—';
const label=v=>String(v??'').replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase());
function register(type,key,data){if(key==null)return '';const ref=type+':'+String(key);store.set(ref,data);return ref}
function valueRow(name,value,extra=''){return '<div class="detail-field"><span>'+esc(name)+'</span><strong class="'+extra+'">'+esc(value==null||value===''?'—':value)+'</strong></div>'}
function section(title,content){return '<section class="detail-section"><span class="detail-kicker">'+esc(title)+'</span><div class="detail-fields">'+content+'</div></section>'}
function renderOrder(o){const customer=o.customer_name||o.name||o.customer?.name||'Customer',phone=o.customer_phone||o.phone||o.customer?.phone;const rows=[valueRow('Order number',o.order_number||o.id),valueRow('Status',label(o.status)),valueRow('Payment',label(o.payment_status)),valueRow('Payment method',o.payment_method),valueRow('Order total',money(o.total)),valueRow('Created',date(o.created_at||o.createdAt)),valueRow('Accepted',date(o.accepted_at)),valueRow('Out for delivery',date(o.out_for_delivery_at)),valueRow('Delivered',date(o.delivered_at))].join('');const delivery=[valueRow('Customer',customer),valueRow('Phone',phone),valueRow('Delivery status',label(o.delivery_status)),valueRow('Delivery address',o.delivery_address),valueRow('Delivery fee',money(o.delivery_fee)),valueRow('Assigned rider',o.rider_name),valueRow('Customer note',o.delivery_note)].join('');return '<div class="detail-hero"><div><span class="detail-kicker">ORDER</span><h2>'+esc(o.order_number||o.id||'Order')+'</h2><p>'+esc(customer)+' · '+esc(phone||'No phone')+'</p></div><span class="detail-status">'+esc(label(o.status||'UNKNOWN'))+'</span></div>'+section('ORDER INFORMATION',rows)+section('CUSTOMER & DELIVERY',delivery)}
function renderIncident(i){const info=[valueRow('Severity',label(i.severity)),valueRow('Status',label(i.status)),valueRow('Source',i.source),valueRow('Dashboard',i.dashboard),valueRow('Restaurant',i.business_name||'Platform'),valueRow('Occurrences',i.occurrences||1),valueRow('First seen',date(i.first_seen_at)),valueRow('Last seen',date(i.last_seen_at)),valueRow('Resolved',date(i.resolved_at))].join('');const stack=i.stack?'<section class="detail-section"><span class="detail-kicker">DIAGNOSTIC CONTEXT</span><pre class="detail-code">'+esc(i.stack)+'</pre></section>':'';const metadata=i.metadata?'<section class="detail-section"><span class="detail-kicker">METADATA</span><pre class="detail-code">'+esc(JSON.stringify(i.metadata,null,2))+'</pre></section>':'';return '<div class="detail-hero"><div><span class="detail-kicker">INCIDENT</span><h2>'+esc(i.message||'Platform issue')+'</h2><p>'+esc(i.business_name||'Platform')+' · '+esc(i.dashboard||i.source||'SYSTEM')+'</p></div><span class="detail-status detail-'+String(i.severity||'ERROR').toLowerCase()+'">'+esc(i.severity||'ERROR')+'</span></div>'+section('INCIDENT INFORMATION',info)+'<section class="detail-section"><span class="detail-kicker">DESCRIPTION</span><div class="detail-message">'+esc(i.message||'No message recorded.')+'</div></section>'+stack+metadata}
function renderRider(r){const info=[valueRow('Name',r.name),valueRow('Phone',r.phone),valueRow('Email',r.email),valueRow('Restaurant',r.business_name),valueRow('Status',label(r.rider_status||r.status)),valueRow('Availability',r.available?'Available':r.online?'Online':'Offline'),valueRow('Vehicle',r.vehicle_type),valueRow('Number plate',r.number_plate),valueRow('Completed trips',r.trip_count),valueRow('Current order',r.order_number),valueRow('Last presence',date(r.presence_updated_at||r.updated_at))].join('');return '<div class="detail-hero"><div><span class="detail-kicker">RIDER</span><h2>'+esc(r.name||'Rider')+'</h2><p>'+esc(r.business_name||'Restaurant')+'</p></div><span class="detail-status">'+esc(label(r.rider_status||'UNKNOWN'))+'</span></div>'+section('RIDER INFORMATION',info)}
function renderRestaurant(b){const info=[valueRow('Restaurant',b.name),valueRow('Slug',b.slug),valueRow('Package',b.plan_name||b.plan_key),valueRow('Status',label(b.status)),valueRow('Website',b.website_url),valueRow('Orders',b.order_count),valueRow('Revenue',money(b.revenue))].join('');return '<div class="detail-hero"><div><span class="detail-kicker">RESTAURANT</span><h2>'+esc(b.name||'Restaurant')+'</h2><p>'+esc(b.slug||'')+'</p></div><span class="detail-status">'+esc(label(b.status||'UNKNOWN'))+'</span></div>'+section('TENANT INFORMATION',info)}
function renderActivity(a){return '<div class="detail-hero"><div><span class="detail-kicker">ACTIVITY</span><h2>'+esc(a.action||'System event')+'</h2><p>'+esc(date(a.created_at))+'</p></div></div>'+section('EVENT',valueRow('Action',a.action)+valueRow('Note',a.note||'System event')+valueRow('Restaurant',a.business_name||'Platform')+valueRow('Time',date(a.created_at)))}
function renderGeneric(data){const entries=Object.entries(data||{}).filter(([k,v])=>v!==undefined&&v!==null&&typeof v!=='object');return '<div class="detail-hero"><div><span class="detail-kicker">DETAIL</span><h2>Record details.</h2></div></div>'+section('INFORMATION',entries.map(([k,v])=>valueRow(label(k),String(v))).join(''))}
function body(type,data){if(type==='order')return renderOrder(data);if(type==='incident')return renderIncident(data);if(type==='rider')return renderRider(data);if(type==='restaurant')return renderRestaurant(data);if(type==='activity')return renderActivity(data);return renderGeneric(data)}
function close(){overlay?.remove();overlay=null}
function open(type,key){const data=store.get(type+':'+String(key));if(!data)return;close();overlay=document.createElement('div');overlay.className='detail-overlay';overlay.innerHTML='<div class="detail-dialog" role="dialog" aria-modal="true" aria-label="Details"><button class="detail-close" type="button" aria-label="Close details">×</button><div class="detail-content">'+body(type,data)+'</div></div>';document.body.appendChild(overlay);overlay.querySelector('.detail-close').onclick=close;overlay.addEventListener('click',e=>{if(e.target===overlay)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()},{once:true})}
document.addEventListener('click',e=>{const trigger=e.target.closest?.('[data-detail-type][data-detail-id]');if(!trigger)return;if(e.target.closest('button,a,input,select,textarea'))return;e.preventDefault();open(trigger.dataset.detailType,trigger.dataset.detailId)});
window.DetailSurface={register,open,close};window.detailRegister=register;
})();