const RIDERS=[{id:'R-001',name:'Daniel Mwangi',vehicle:'Motorbike',plate:'KDA 123A',phone:'0700 000 001',available:true,trips:0},{id:'R-002',name:'Brian Otieno',vehicle:'Motorbike',plate:'KDB 456B',phone:'0700 000 002',available:true,trips:0},{id:'R-003',name:'Kevin Kiptoo',vehicle:'Car',plate:'KDC 789C',phone:'0700 000 003',available:true,trips:0}];
function riders(){return read('doe_riders',RIDERS)}
function saveRiders(v){write('doe_riders',v)}
function syncRiderAvailability(){const rs=riders();const os=read('doe_orders',[]);rs.forEach(r=>r.available=!os.some(o=>o.riderId===r.id&&o.status==='Out for delivery'));saveRiders(rs);return rs}
function assignRider(orderId,riderId){const os=read('doe_orders',[]),rs=syncRiderAvailability();const o=os.find(x=>x.id===orderId),r=rs.find(x=>x.id===riderId);if(!o||!r||!r.available||o.status!=='Accepted')return false;o.riderId=r.id;o.riderName=r.name;o.riderVehicle=r.vehicle;o.riderPlate=r.plate;o.riderPhone=r.phone;o.status='Out for delivery';o.deliveryStarted=new Date().toISOString();write('doe_orders',os);syncRiderAvailability();return true}
function markDelivered(orderId,source='rider'){const os=read('doe_orders',[]),o=os.find(x=>x.id===orderId);if(!o||o.status!=='Out for delivery')return false;o.status='Delivered';o.deliveryConfirmedBy=source;o.deliveredAt=new Date().toISOString();o.receiptNo='RCPT-'+o.id;write('doe_orders',os);if(o.riderId){const rs=riders(),r=rs.find(x=>x.id===o.riderId);if(r){r.trips=(r.trips||0)+1;r.available=true;saveRiders(rs)}}return true}
function renderRider(){const el=document.getElementById('rider-view');if(!el)return;syncRiderAvailability();const rs=riders();const active=read('doe_orders',[]).find(o=>o.status==='Out for delivery'&&o.riderId==='R-001');el.innerHTML=`<div class="dashboard-head"><div><p class="eyebrow">DELIVERY PORTAL</p><h1>Rider dashboard.</h1><p class="muted">Prototype sign-in and delivery workflow</p></div></div><section class="panel"><h2>Rider sign in</h2><div class="field"><label>Rider ID</label><input id="rider-id" value="R-001"></div><div class="field"><label>Access code</label><input id="rider-code" type="password" value="demo"></div><button class="btn" onclick="showRiderJob()">Sign in</button></section><div id="rider-job" class="panel" style="margin-top:1rem"></div>`;if(active)showRiderJob()}
function showRiderJob(){const el=document.getElementById('rider-job');if(!el)return;const id=document.getElementById('rider-id').value.trim();const o=read('doe_orders',[]).find(x=>x.riderId===id&&x.status==='Out for delivery');const r=riders().find(x=>x.id===id);el.innerHTML=o?`<p class="eyebrow">ACTIVE DELIVERY</p><h2>${o.id} · ${o.customer}</h2><p>${o.note||'No delivery note'}</p><p><strong>${r.name}</strong> · ${r.vehicle} · ${r.plate}</p><button class="btn" onclick="riderComplete('${o.id}')">MARK DELIVERED</button>`:`<p class="eyebrow">NO ACTIVE DELIVERY</p><h2>You're available.</h2><p class="muted">Trips completed: ${r?r.trips||0:0}</p>`}
function riderComplete(id){markDelivered(id,'rider');renderRider()}
renderRider();
