const API='https://restaurant-ordering-api-ow3p.onrender.com',KEY='savanna_station_session';let S=null,D={station:null,orders:[],riders:[]},selected={};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=v=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES'}).format(Number(v||0));
function session(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
async function api(path,o={}){const r=await fetch(API+path,{...o,headers:{'Content-Type':'application/json',Authorization:'Bearer '+S.token,...(o.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok){if(r.status===401){localStorage.removeItem(KEY);location.href='connect-device.html';}throw new Error(d.error||'Request failed')}return d}
async function load(){S=session();if(!S?.token){location.href='connect-device.html';return}try{D.station=await api('/api/station/me');D.orders=await api('/api/station/orders');D.riders=(D.station.mode==='OPERATIONS'||D.station.mode==='COUNTER')?await api('/api/station/riders'):[];render();}catch(e){document.getElementById('station-view').innerHTML='<section class="connect-card"><h1>Station unavailable</h1><p>'+esc(e.message)+'</p><button class="station-btn" onclick="load()">RETRY</button></section>';}}
function sortRiders(a){return [...a].sort((x,y)=>{if(Boolean(x.available)!==Boolean(y.available))return x.available?-1:1;const X=x.last_completed_at?new Date(x.last_completed_at).getTime():0,Y=y.last_completed_at?new Date(y.last_completed_at).getTime():0;if(!X&&!Y)return Number(x.trip_count||0)-Number(y.trip_count||0);if(!X)return -1;if(!Y)return 1;return X-Y})}
function orderCard(o){let action='';if(['OPERATIONS','COUNTER'].includes(D.station.mode)&&o.status==='NEW'&&o.payment_status==='PAID')action='<button class="station-btn" onclick="acceptOrder(\''+o.id+'\',this)">✓ ACCEPT ORDER</button>';else if(['OPERATIONS','COUNTER'].includes(D.station.mode)&&o.status==='ACCEPTED')action=dispatch(o);else if(o.status==='OUT_FOR_DELIVERY')action='<div class="station-complete">● DELIVERY IN PROGRESS</div>';else action='<div class="station-muted">'+esc(o.status)+' · '+esc(o.payment_status)+'</div>';return '<article class="station-order"><div><div class="station-order-top"><b>'+esc(o.order_number)+'</b><span>'+new Date(o.created_at).toLocaleString('en-KE',{dateStyle:'medium',timeStyle:'short'})+'</span></div><h3>'+esc(o.name)+'</h3><p>'+esc(o.phone)+'</p>'+(o.delivery_note?'<div class="station-note">'+esc(o.delivery_note)+'</div>':'')+'</div><aside><strong>'+money(o.total)+'</strong><small>'+esc(o.payment_method||'PAYMENT')+'</small>'+action+'</aside></article>'}
function dispatch(o){const selectedR=selected[o.id]||'';return '<div class="station-dispatch"><span>SELECT RIDER</span><div class="station-riders">'+sortRiders(D.riders).map((r,i)=>'<button class="station-rider '+(r.available?'':'off')+(selectedR===r.id?' selected':'')+'" '+(r.available?'onclick="selectRider(\''+o.id+'\',\''+r.id+'\')"':'disabled')+'><b>'+(r.profile_image_url?'<img src="'+esc(r.profile_image_url)+'" alt="">':esc((r.name||'?')[0]))+'</b><strong>'+esc(r.name)+'</strong><small>● '+(r.available?'AVAILABLE':'UNAVAILABLE')+'</small>'+(i===0&&r.available?'<em>PRIORITY</em>':'')+'</button>').join('')+'</div><button class="station-btn" '+(selectedR?'':'disabled')+' onclick="assignRider(\''+o.id+'\',this)">ASSIGN RIDER</button></div>'}
function selectRider(id,r){selected[id]=r;render();}
async function acceptOrder(id,b){b.disabled=true;b.textContent='ACCEPTING…';try{await api('/api/station/orders/'+id+'/status',{method:'POST',body:JSON.stringify({status:'ACCEPTED'})});await load()}catch(e){b.disabled=false;b.textContent='✓ ACCEPT ORDER';alert(e.message)}}
async function assignRider(id,b){const riderId=selected[id];if(!riderId)return;b.disabled=true;b.textContent='ASSIGNING…';try{await api('/api/station/orders/'+id+'/assign-rider',{method:'POST',body:JSON.stringify({riderId})});delete selected[id];await load()}catch(e){b.disabled=false;b.textContent='ASSIGN RIDER';alert(e.message)}}
function render(){const s=D.station,o=D.orders||[];document.getElementById('station-view').innerHTML='<section class="station-shell"><header class="station-header"><div><span class="eyebrow">'+esc(window.TenantTheme?.name?.()||'RESTAURANT')+' · ORDER CONTROL</span><h1>'+esc(s.name)+'</h1><p>'+esc(s.deviceType)+' · '+esc(s.mode)+' · <span class="station-live">● CONNECTED</span></p></div><button class="station-btn secondary" onclick="disconnect()">DISCONNECT</button></header><section class="station-summary"><b>'+o.filter(x=>x.status==='NEW'&&x.payment_status==='PAID').length+'<span>NEW PAID</span></b><b>'+o.filter(x=>x.status==='ACCEPTED').length+'<span>ACCEPTED</span></b><b>'+o.filter(x=>x.status==='OUT_FOR_DELIVERY').length+'<span>OUT FOR DELIVERY</span></b></section><section class="station-orders">'+(o.map(orderCard).join('')||'<div class="station-empty">No orders yet.</div>')+'</section></section>'}
async function disconnect(){try{await api('/api/station/logout',{method:'POST'});}catch{}localStorage.removeItem(KEY);location.href='connect-device.html';}
function startEvents(){if(!S?.token)return;const es=new EventSource(API+'/api/station/events?stationToken='+encodeURIComponent(S.token));['order.updated','rider.updated','delivery.updated','refund.updated'].forEach(name=>es.addEventListener(name,()=>load()));es.onerror=()=>{};}
async function heartbeat(){if(S?.token)try{await api('/api/station/heartbeat',{method:'POST'})}catch{}}
(window.TenantTheme?.ready||Promise.resolve()).then(()=>load()).then(()=>{startEvents();setInterval(heartbeat,300000);});