const API='https://restaurant-ordering-api-ow3p.onrender.com',KEY='savanna_station_session';let S=null,D={station:null,orders:[],riders:[]},selected={},filter='NEW',search='';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=v=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES'}).format(Number(v||0));
function session(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
async function api(path,o={}){const r=await fetch(API+path,{...o,headers:{'Content-Type':'application/json',Authorization:'Bearer '+S.token,...(o.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok){if(r.status===401){localStorage.removeItem(KEY);location.href='connect-device.html'}throw new Error(d.error||'Request failed')}return d}
async function load(){S=session();if(!S?.token){location.href='connect-device.html';return}try{D.station=await api('/api/station/me');D.orders=await api('/api/station/orders');D.riders=['OPERATIONS','COUNTER'].includes(D.station.mode)?await api('/api/station/riders'):[];render()}catch(e){document.getElementById('station-view').innerHTML='<section class="station-error"><b>STATION OFFLINE</b><h1>Unable to load orders.</h1><p>'+esc(e.message)+'</p><button class="station-btn" onclick="load()">RETRY</button></section>'}}
function sortRiders(a){return[...a].sort((x,y)=>{if(Boolean(x.available)!==Boolean(y.available))return x.available?-1:1;const X=x.last_completed_at?new Date(x.last_completed_at).getTime():0,Y=y.last_completed_at?new Date(y.last_completed_at).getTime():0;if(!X&&!Y)return Number(x.trip_count||0)-Number(y.trip_count||0);if(!X)return-1;if(!Y)return 1;return X-Y})}
function counts(){const o=D.orders||[];return{NEW:o.filter(x=>x.status==='NEW'&&x.payment_status==='PAID').length,ACCEPTED:o.filter(x=>x.status==='ACCEPTED').length,OUT_FOR_DELIVERY:o.filter(x=>x.status==='OUT_FOR_DELIVERY').length,DELIVERED:o.filter(x=>x.status==='DELIVERED').length,CANCELLED:o.filter(x=>x.status==='CANCELLED').length,ALL:o.length}}
function selectRider(id,r){selected[id]=r;render()}
function riderPicker(o){const sr=selected[o.id]||'';return '<div class="station-dispatch"><div class="dispatch-label">AVAILABLE RIDERS <span>Longest wait gets priority</span></div><div class="station-riders">'+sortRiders(D.riders).map((r,i)=>'<button type="button" class="station-rider '+(r.available?'':'off')+(sr===r.id?' selected':'')+'" '+(r.available?'onclick="selectRider(&quot;'+o.id+'&quot;,&quot;'+r.id+'&quot;)"':'disabled')+'><b>'+(r.profile_image_url?'<img src="'+esc(r.profile_image_url)+'" alt="">':esc((r.name||'?')[0]))+'</b><strong>'+esc(r.name)+'</strong><small>'+esc(r.vehicle_type||'Vehicle')+'</small><em>'+(r.available?(i===0?'PRIORITY':'AVAILABLE'):'UNAVAILABLE')+'</em></button>').join('')+'</div><button type="button" class="station-btn assign '+(sr?'':'disabled')+'" '+(sr?'onclick="assignRider(&quot;'+o.id+'&quot;,this)"':'disabled')+'>ASSIGN RIDER</button></div>'}
function orderCard(o){let a='';if(['OPERATIONS','COUNTER'].includes(D.station.mode)&&o.status==='NEW'&&o.payment_status==='PAID')a='<button class="station-btn action" onclick="acceptOrder(&quot;'+o.id+'&quot;,this)">✓ ACCEPT ORDER</button>';else if(['OPERATIONS','COUNTER'].includes(D.station.mode)&&o.status==='ACCEPTED')a=riderPicker(o);else if(o.status==='OUT_FOR_DELIVERY')a='<div class="station-state active">● DELIVERY IN PROGRESS</div>';else if(o.status==='DELIVERED')a='<div class="station-state done">✓ COMPLETED</div>';else if(o.status==='CANCELLED')a='<div class="station-state">CANCELLED</div>';else a='<div class="station-state">AWAITING PAYMENT</div>';
return '<article class="station-order '+(o.status==='NEW'&&o.payment_status==='PAID'?'new':'')+'"><div class="order-main"><div class="order-top"><div><b>'+esc(o.order_number)+'</b><span>'+new Date(o.created_at).toLocaleString('en-KE',{dateStyle:'medium',timeStyle:'short'})+'</span></div><span class="status-chip '+o.status.toLowerCase()+'">'+esc(o.status==='NEW'?'NEW ORDER':o.status)+'</span></div>'+(o.payment_status==='PAID'?'<div class="payment-confirmed"><span>✓ PAYMENT CONFIRMED</span><span>'+esc(o.payment_method||'Card')+'</span></div>':'')+'<div class="customer-line"><div class="customer-avatar">'+esc((o.name||'?')[0])+'</div><div><b>'+esc(o.name)+'</b><span>'+esc(o.phone)+'</span></div></div>'+(o.delivery_note?'<div class="station-note"><b>Customer note</b><span>'+esc(o.delivery_note)+'</span></div>':'')+'</div><aside class="order-side"><span>ORDER TOTAL</span><strong>'+money(o.total)+'</strong><small>'+esc(o.payment_status)+' · '+esc(o.payment_method||'Card')+'</small>'+a+'</aside></article>'}
function render(){const s=D.station,o=D.orders||[],c=counts(),q=search.trim().toLowerCase(),list=o.filter(x=>{const ok=filter==='NEW'?(x.status==='NEW'&&x.payment_status==='PAID'):filter==='ALL'?true:x.status===filter;return ok&&(!q||[x.order_number,x.name,x.phone,x.email].some(v=>String(v||'').toLowerCase().includes(q)))}).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));const labels={NEW:'New',ACCEPTED:'Preparing',OUT_FOR_DELIVERY:'Delivery',DELIVERED:'Completed',CANCELLED:'Cancelled',ALL:'All'};document.getElementById('station-view').innerHTML='<section class="station-shell"><header class="station-header"><div><span class="station-kicker"><i></i> LIVE ORDER STATION</span><h1>Orders.</h1><p>'+esc(s.name)+' · '+esc(s.deviceType)+' · '+esc(s.mode)+'</p></div><div class="station-actions"><span class="connection-badge"><i></i> CONNECTED</span><button class="station-btn secondary" onclick="load()">↻ REFRESH</button><button class="station-btn secondary" onclick="disconnect()">DISCONNECT</button></div></header><section class="station-summary"><article class="accent"><span>NEW PAID ORDERS</span><strong>'+c.NEW+'</strong><small>Need restaurant action</small></article><article><span>PREPARING</span><strong>'+c.ACCEPTED+'</strong><small>Accepted orders</small></article><article><span>OUT FOR DELIVERY</span><strong>'+c.OUT_FOR_DELIVERY+'</strong><small>Currently with riders</small></article><article><span>COMPLETED</span><strong>'+c.DELIVERED+'</strong><small>Delivered orders</small></article></section><div class="station-toolbar"><div class="station-filters">'+[['NEW','New'],['ACCEPTED','Preparing'],['OUT_FOR_DELIVERY','Delivery'],['DELIVERED','Completed'],['CANCELLED','Cancelled'],['ALL','All']].map(x=>'<button class="station-filter '+(filter===x[0]?'active':'')+'" onclick="filter=&quot;'+x[0]+'&quot;;render()">'+x[1]+' <b>'+c[x[0]]+'</b></button>').join('')+'</div><div class="station-search"><input id="station-search" value="'+esc(search)+'" placeholder="Search order, customer or phone" onkeydown="if(event.key===&quot;Enter&quot;){search=this.value;render()}"><button class="station-btn" onclick="search=document.getElementById(&quot;station-search&quot;).value;render()">SEARCH</button></div></div><div class="station-status-strip"><span><i></i><b>System online</b> Real-time connection active</span><span><b>'+o.filter(x=>x.payment_status==='PAID').length+'</b> paid orders</span><span><b>'+o.filter(x=>x.payment_status!=='PAID').length+'</b> awaiting payment</span><span><b>'+D.riders.filter(x=>x.available).length+'</b> riders available</span></div><div class="station-list-heading"><div><span class="station-eyebrow">'+labels[filter].toUpperCase()+'</span><h2>'+list.length+' orders</h2></div><small>Live · synced automatically</small></div><section class="station-orders">'+(list.map(orderCard).join('')||'<div class="station-empty">No orders match this view.</div>')+'</section></section>'}
async function acceptOrder(id,b){b.disabled=true;b.textContent='ACCEPTING…';try{await api('/api/station/orders/'+id+'/status',{method:'POST',body:JSON.stringify({status:'ACCEPTED'})});await load()}catch(e){b.disabled=false;b.textContent='✓ ACCEPT ORDER';alert(e.message)}}
async function assignRider(id,b){const riderId=selected[id];if(!riderId)return;b.disabled=true;b.textContent='ASSIGNING…';try{await api('/api/station/orders/'+id+'/assign-rider',{method:'POST',body:JSON.stringify({riderId})});delete selected[id];await load()}catch(e){b.disabled=false;b.textContent='ASSIGN RIDER';alert(e.message)}}
async function disconnect(){try{await api('/api/station/logout',{method:'POST'});}catch{}localStorage.removeItem(KEY);location.href='connect-device.html'}
function startEvents(){if(!S?.token)return;const es=new EventSource(API+'/api/station/events?stationToken='+encodeURIComponent(S.token));es.addEventListener('order.updated',()=>load());es.onerror=()=>{}}
async function heartbeat(){if(S?.token)try{await api('/api/station/heartbeat',{method:'POST'})}catch{}}
load().then(()=>{startEvents();setInterval(heartbeat,300000)});