import dns from 'node:dns/promises';
import net from 'node:net';

const DEFAULT_BRANDING={display_name:'',logo_url:'',favicon_url:'',primary_color:'#176b32',secondary_color:'#172019',accent_color:'#d56a2d',background_color:'#f5f5f0',text_color:'#172019',font_family:'Inter,system-ui,-apple-system,"Segoe UI",sans-serif',website_detected_name:'',source_url:'',source_title:'',source_description:'',source_logo_url:'',imported_at:null};
function clean(v){return String(v||'').replace(/\s+/g,' ').trim();}
function meta(html,name){const n=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const a=new RegExp('<meta[^>]+(?:name|property)\\s*=\\s*["\\']'+n+'["\\'][^>]*content\\s*=\\s*["\\']([^"\\']+)["\\'][^>]*>','i');const b=new RegExp('<meta[^>]+content\\s*=\\s*["\\']([^"\\']+)["\\'][^>]+(?:name|property)\\s*=\\s*["\\']'+n+'["\\']','i');return (html.match(a)||html.match(b)||[])[1]||'';}
function titleText(html){return clean(((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||'').replace(/<[^>]+>/g,' '));}
function resolveUrl(raw,base){try{return new URL(String(raw||''),base).toString();}catch{return '';}}
function privateIp(ip){if(net.isIPv4(ip)){const p=ip.split('.').map(Number);return p[0]===10||p[0]===127||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]===169&&p[1]===254)||p[0]===0;}if(net.isIPv6(ip)){const x=ip.toLowerCase();return x==='::1'||x.startsWith('fc')||x.startsWith('fd')||x.startsWith('fe80:');}return true;}
async function publicUrl(raw){const u=new URL(raw);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw new Error('Website URL must be a public http or https URL.');const host=u.hostname.toLowerCase();if(host==='localhost'||host.endsWith('.local')||(net.isIP(host)&&privateIp(host)))throw new Error('That website address is not a public website.');const ips=await dns.lookup(host,{all:true});if(!ips.length||ips.some(x=>privateIp(x.address)))throw new Error('That website resolves to a private network address.');return u;}
async function fetchText(raw,maxBytes){const u=await publicUrl(raw);const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),7000);try{const r=await fetch(u,{signal:controller.signal,redirect:'follow',headers:{'user-agent':'RestaurantOrderingPlatformBrandImporter/1.0'}});if(!r.ok)throw new Error('Website returned HTTP '+r.status);const type=String(r.headers.get('content-type')||'');if(type&&!/text\/(html|css)|application\/(xhtml\+xml|css)/i.test(type))throw new Error('The homepage did not return HTML.');const text=await r.text();return {text:text.slice(0,maxBytes||900000),url:r.url||u.toString()};}finally{clearTimeout(timer);}}
async function cssLinks(html,base){const links=[];const re=/<link[^>]+rel=["\'][^"\']*stylesheet[^"\']*["\'][^>]+href=["\']([^"\']+)["\'][^>]*>/gi;let m;while((m=re.exec(html))&&links.length<4)links.push(resolveUrl(m[1],base));const out=[];for(const link of links){try{out.push((await fetchText(link,500000)).text);}catch{}}return out.join('\n');}
function colors(text){const counts=new Map();const add=c=>{let v=String(c||'').toLowerCase();if(v.length===4)v='#'+v.slice(1).split('').map(x=>x+x).join('');if(!/^#[0-9a-f]{6}$/.test(v))return;const rgb=[parseInt(v.slice(1,3),16),parseInt(v.slice(3,5),16),parseInt(v.slice(5,7),16)],max=Math.max(...rgb),min=Math.min(...rgb);if(max-min<18||max<35||min>238)return;counts.set(v,(counts.get(v)||0)+1);};for(const m of text.matchAll(/#[0-9a-f]{3,8}\b/gi))add(m[0].slice(0,7));return [...counts.entries()].sort((a,b)=>b[1]-a[1]).map(x=>x[0]);}
function lum(hex){const a=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255).map(v=>v<=.03928?v/12.92:Math.pow((v+.055)/1.055,2.4));return .2126*a[0]+.7152*a[1]+.0722*a[2];}
function palette(list,theme){const primary=/^#[0-9a-f]{6}$/i.test(theme)?theme:(list[0]||DEFAULT_BRANDING.primary_color);const secondary=list.find(x=>x!==primary)||DEFAULT_BRANDING.secondary_color;const accent=list.find(x=>x!==primary&&x!==secondary)||primary;return {primary,secondary,accent,background:'#f5f5f0',text:lum(primary)>.55?'#172019':'#ffffff'};}
function extractBrand(html,css,source){const all=html+'\n'+css;const theme=meta(html,'theme-color');const title=titleText(html);const detected=meta(html,'og:site_name')||meta(html,'application-name')||title.split(/[|•—-]/)[0]||'';const desc=meta(html,'description')||meta(html,'og:description');const logoMeta=meta(html,'og:image')||meta(html,'twitter:image');const logoImg=(html.match(/<img[^>]+(?:alt=["\'][^"\']*logo[^"\']*["\']|class=["\'][^"\']*logo[^"\']*["\'])[^>]+src=["\']([^"\']+)["\'][^>]*>/i)||[])[1]||'';const icon=(html.match(/<link[^>]+rel=["\'][^"\']*(?:icon|apple-touch-icon)[^"\']*["\'][^>]+href=["\']([^"\']+)["\'][^>]*>/i)||[])[1]||'';const p=palette(colors(all),theme);const font=(all.match(/font-family\s*:\s*([^;}{]+)/i)||[])[1];return {detectedName:clean(detected),description:clean(desc),title:clean(title),logoUrl:resolveUrl(logoMeta||logoImg,source),faviconUrl:resolveUrl(icon,source),primaryColor:p.primary,secondaryColor:p.secondary,accentColor:p.accent,backgroundColor:p.background,textColor:p.text,fontFamily:font?font.trim():DEFAULT_BRANDING.font_family};}
async function getBranding(pool,id){const r=await pool.query('select b.id,b.name,b.pickup_address,rb.* from businesses b left join restaurant_branding rb on rb.business_id=b.id where b.id=$1',[id]);if(!r.rowCount)return null;const x=r.rows[0];return {...DEFAULT_BRANDING,...x,display_name:x.display_name||x.name};}
export function registerBrandingEngine(app,pool,{requireControl,requireManager,broadcastRealtime}){
app.get('/api/businesses/:id/branding',async(req,res)=>{try{const branding=await getBranding(pool,String(req.params.id));if(!branding)return res.status(404).json({error:'Restaurant not found'});res.json({branding});}catch(e){res.status(500).json({error:e.message||'Unable to load restaurant branding'});}});
app.post('/api/control/businesses/:id/branding/import',requireControl,async(req,res)=>{try{const id=String(req.params.id);const b=await pool.query('select id,name from businesses where id=$1',[id]);if(!b.rowCount)return res.status(404).json({error:'Restaurant not found'});const url=String(req.body.websiteUrl||'').trim();if(!url)throw new Error('Enter the restaurant homepage URL first.');const page=await fetchText(url,900000);const css=await cssLinks(page.text,page.url);const f=extractBrand(page.text,css,page.url);await pool.query("insert into restaurant_branding(business_id,display_name,logo_url,favicon_url,primary_color,secondary_color,accent_color,background_color,text_color,font_family,website_detected_name,source_url,source_title,source_description,source_logo_url,imported_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,now()) on conflict(business_id) do update set logo_url=excluded.logo_url,favicon_url=excluded.favicon_url,primary_color=excluded.primary_color,secondary_color=excluded.secondary_color,accent_color=excluded.accent_color,background_color=excluded.background_color,text_color=excluded.text_color,font_family=excluded.font_family,website_detected_name=excluded.website_detected_name,source_url=excluded.source_url,source_title=excluded.source_title,source_description=excluded.source_description,source_logo_url=excluded.source_logo_url,imported_at=now(),updated_at=now()",[id,b.rows[0].name,f.logoUrl,f.faviconUrl,f.primaryColor,f.secondaryColor,f.accentColor,f.backgroundColor,f.textColor,f.fontFamily,f.detectedName,page.url,f.title,f.description,f.logoUrl]);const branding=await getBranding(pool,id);broadcastRealtime?.({businessId:id,event:'branding.updated',data:{businessId:id}});res.json({branding,detected:f});}catch(e){res.status(400).json({error:e.name==='AbortError'?'Website took too long to respond':e.message||'Unable to import website branding'});}});
app.patch('/api/manager/branding',requireManager,async(req,res)=>{try{const id=String(req.manager.business_id),current=await getBranding(pool,id);const map={primaryColor:'primary_color',secondaryColor:'secondary_color',accentColor:'accent_color',backgroundColor:'background_color',textColor:'text_color',fontFamily:'font_family',logoUrl:'logo_url',faviconUrl:'favicon_url'};const v=k=>req.body[k]!==undefined?String(req.body[k]).trim():current[map[k]];await pool.query("insert into restaurant_branding(business_id,display_name,logo_url,favicon_url,primary_color,secondary_color,accent_color,background_color,text_color,font_family,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,now()) on conflict(business_id) do update set logo_url=excluded.logo_url,favicon_url=excluded.favicon_url,primary_color=excluded.primary_color,secondary_color=excluded.secondary_color,accent_color=excluded.accent_color,background_color=excluded.background_color,text_color=excluded.text_color,font_family=excluded.font_family,updated_at=now()",[id,current.display_name||current.name,v('logoUrl'),v('faviconUrl'),v('primaryColor')||DEFAULT_BRANDING.primary_color,v('secondaryColor')||DEFAULT_BRANDING.secondary_color,v('accentColor')||DEFAULT_BRANDING.accent_color,v('backgroundColor')||DEFAULT_BRANDING.background_color,v('textColor')||DEFAULT_BRANDING.text_color,v('fontFamily')||DEFAULT_BRANDING.font_family]);const branding=await getBranding(pool,id);broadcastRealtime?.({businessId:id,event:'branding.updated',data:{businessId:id}});res.json({branding});}catch(e){res.status(400).json({error:e.message||'Unable to save branding'});}});
}
export {DEFAULT_BRANDING,getBranding};