const num=v=>Number(v||0);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const clean=(v,n=200)=>String(v??'').trim().slice(0,n);
export function registerIntelligence(app,pool){
  async function manager(req,res,next){
    try{const raw=String(req.headers.authorization||'');if(!raw.startsWith('Bearer '))return res.status(401).json({error:'Manager session required'});const crypto=await import('node:crypto');const hash=crypto.createHash('sha256').update(raw.slice(7).trim()).digest('hex');const r=await pool.query(`select ms.manager_id,mu.business_id,mu.role from manager_sessions ms join manager_users mu on mu.id=ms.manager_id where ms.token_hash=$1 and ms.expires_at>now() and mu.active=true limit 1`,[hash]);if(!r.rowCount)return res.status(401).json({error:'Manager session expired'});req.manager={id:r.rows[0].manager_id,businessId:r.rows[0].business_id,role:r.rows[0].role};next()}catch{res.status(500).json({error:'Unable to verify manager session'})}
  }
  async function metrics(businessId,days=28){const r=await pool.query(`select date_trunc('day',created_at)::date as metric_day,coalesce(sum(total) filter(where payment_status='PAID'),0) revenue,count(*) orders_count,count(*) filter(where status='DELIVERED') completed_orders from orders where business_id=$1 and created_at>=current_date-($2::int) group by 1 order by 1`,[businessId,days]);return r.rows.map(x=>({day:String(x.metric_day),revenue:num(x.revenue),orders:num(x.orders_count),completedOrders:num(x.completed_orders)}))}
  app.get('/api/manager/intelligence/overview',manager,async(req,res)=>{try{const days=clamp(num(req.query.days)||28,7,90),daily=await metrics(req.manager.businessId,days),revenue=daily.reduce((s,x)=>s+x.revenue,0),orders=daily.reduce((s,x)=>s+x.orders,0),completed=daily.reduce((s,x)=>s+x.completedOrders,0),aov=orders?revenue/orders:0,recent=daily.slice(-7),prior=daily.slice(-14,-7),recentRev=recent.reduce((s,x)=>s+x.revenue,0),priorRev=prior.reduce((s,x)=>s+x.revenue,0);res.json({periodDays:days,daily,revenue,orders,completedOrders:completed,averageOrderValue:aov,recent7DayRevenue:recentRev,previous7DayRevenue:priorRev,revenueChangePct:priorRev?((recentRev-priorRev)/priorRev)*100:null})}catch(e){res.status(500).json({error:e.message||'Unable to load intelligence'})}});
  app.get('/api/manager/intelligence/ai',manager,async(req,res)=>{try{const daily=await metrics(req.manager.businessId,28),orders=await pool.query(`select oi.product_id,oi.product_name,sum(oi.quantity)::numeric quantity,sum(oi.quantity*oi.unit_price)::numeric revenue from order_items oi join orders o on o.id=oi.order_id where o.business_id=$1 and o.created_at>=current_date-interval '28 days' and o.payment_status='PAID' group by oi.product_id,oi.product_name order by revenue desc limit 20`,[req.manager.businessId]),avgDaily=daily.length?daily.reduce((s,x)=>s+x.revenue,0)/daily.length:0,recent=daily.slice(-7).reduce((s,x)=>s+x.revenue,0)/7,direction=recent>avgDaily*1.1?'growing':recent<avgDaily*.9?'softening':'stable',top=orders.rows.slice(0,5).map(x=>({productId:x.product_id,name:x.product_name,revenue:num(x.revenue),quantity:num(x.quantity)})),recommendations=[];if(direction==='growing')recommendations.push({type:'DEMAND',priority:'HIGH',title:'Demand is rising',detail:'Recent weekly revenue is materially above the 28-day baseline. Review stock and staffing capacity before peak periods.'});if(direction==='softening')recommendations.push({type:'DEMAND',priority:'MEDIUM',title:'Demand is softening',detail:'Recent weekly revenue is below the 28-day baseline. Review promotions, menu availability and customer demand before increasing inventory.'});if(top[0])recommendations.push({type:'MENU',priority:'MEDIUM',title:'Protect your strongest sellers',detail:top[0].name+' is currently the highest-revenue item in the measured period.'});if(!recommendations.length)recommendations.push({type:'OPERATIONS',priority:'LOW',title:'Operations are broadly stable',detail:'No major directional signal was detected in the current sales window.'});res.json({engine:'rules-based intelligence',direction,averageDailyRevenue:avgDaily,recentDailyRevenue:recent,topProducts:top,recommendations})}catch(e){res.status(500).json({error:e.message||'Unable to generate intelligence'})}});
  app.get('/api/manager/intelligence/profit',manager,async(req,res)=>{try{const r=await pool.query(`select p.id,p.name,p.price,coalesce(s.unit_cost,0) unit_cost,coalesce(sum(oi.quantity),0)::numeric quantity,coalesce(sum(oi.quantity*oi.unit_price),0)::numeric revenue from products p left join intelligence_product_settings s on s.product_id=p.id and s.business_id=p.business_id left join order_items oi on oi.product_id=p.id left join orders o on o.id=oi.order_id and o.business_id=p.business_id and o.created_at>=current_date-interval '28 days' and o.payment_status='PAID' where p.business_id=$1 group by p.id,p.name,p.price,s.unit_cost order by revenue desc`,[req.manager.businessId]);const items=r.rows.map(x=>{const price=num(x.price),cost=num(x.unit_cost),margin=price-cost,marginPct=price?(margin/price)*100:0,suggested=cost?cost/.65:null;return {...x,price,cost,margin,marginPct,quantity:num(x.quantity),revenue:num(x.revenue),suggestedPrice:suggested?Math.ceil(suggested/5)*5:null}});res.json({periodDays:28,items})}catch(e){res.status(500).json({error:e.message||'Unable to calculate profit optimization'})}});
  app.get('/api/manager/intelligence/demand',manager,async(req,res)=>{try{const rows=await pool.query(`select extract(isodow from created_at)::int dow,date_trunc('day',created_at)::date day,count(*)::int orders,coalesce(sum(total) filter(where payment_status='PAID'),0)::numeric revenue from orders where business_id=$1 and created_at>=current_date-interval '56 days' group by 1,2 order by 2`,[req.manager.businessId]),byDow={};for(const r of rows.rows){byDow[r.dow]??=[];byDow[r.dow].push({orders:num(r.orders),revenue:num(r.revenue),day:String(r.day)})}const forecast=Array.from({length:7},(_,i)=>{const a=byDow[i+1]||[],avg=a.length?a.reduce((s,x)=>s+x.orders,0)/a.length:0,rev=a.length?a.reduce((s,x)=>s+x.revenue,0)/a.length:0;return {dayOfWeek:i+1,forecastOrders:Math.round(avg),forecastRevenue:Math.round(rev*100)/100,sampleDays:a.length}});res.json({method:'same-weekday rolling average',historyDays:56,forecast})}catch(e){res.status(500).json({error:e.message||'Unable to forecast demand'})}});
  app.get('/api/manager/intelligence/inventory',manager,async(req,res)=>{try{const r=await pool.query(`select p.id,p.name,coalesce(s.stock_on_hand,0) stock_on_hand,coalesce(s.reorder_point,0) reorder_point,coalesce(s.lead_time_days,1) lead_time_days,coalesce(s.target_days,7) target_days,coalesce(sum(oi.quantity) filter(where o.created_at>=current_date-interval '28 days'),0)::numeric units_28 from products p left join intelligence_product_settings s on s.product_id=p.id and s.business_id=p.business_id left join order_items oi on oi.product_id=p.id left join orders o on o.id=oi.order_id and o.business_id=p.business_id where p.business_id=$1 group by p.id,p.name,s.stock_on_hand,s.reorder_point,s.lead_time_days,s.target_days order by units_28 desc`,[req.manager.businessId]);const items=r.rows.map(x=>{const daily=num(x.units_28)/28,lead=daily*num(x.lead_time_days),target=daily*num(x.target_days),stock=num(x.stock_on_hand),reorder=Math.max(num(x.reorder_point),lead);return {...x,stock_on_hand:stock,daily_velocity:daily,lead_time_demand:lead,target_stock:target,reorder_quantity:Math.max(0,target-stock),status:stock<=reorder?'REORDER':'OK'}});res.json({method:'28-day sales velocity',items})}catch(e){res.status(500).json({error:e.message||'Unable to forecast inventory'})}});
  app.get('/api/manager/intelligence/anomalies',manager,async(req,res)=>{try{const d=await metrics(req.manager.businessId,35),vals=d.slice(0,-7).map(x=>x.revenue),mean=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0,sd=vals.length?Math.sqrt(vals.reduce((s,v)=>s+(v-mean)**2,0)/vals.length):0,anomalies=d.slice(-7).map(x=>{const z=sd?Math.abs(x.revenue-mean)/sd:0;return {...x,expectedRevenue:mean,zScore:z,severity:z>=3?'HIGH':z>=2?'MEDIUM':z>=1.5?'LOW':null}}).filter(x=>x.severity);res.json({baselineDays:28,meanRevenue:mean,standardDeviation:sd,anomalies})}catch(e){res.status(500).json({error:e.message||'Unable to detect anomalies'})}});
  app.get('/api/manager/intelligence/benchmarks',manager,async(req,res)=>{try{const branches=await pool.query(`select b.id,b.name,b.code,coalesce(sum(o.total) filter(where o.payment_status='PAID' and o.created_at>=current_date-interval '28 days'),0)::numeric revenue,count(o.id)::int orders from restaurant_branches b left join orders o on o.branch_id=b.id and o.created_at>=current_date-interval '28 days' where b.business_id=$1 group by b.id,b.name,b.code order by revenue desc`,[req.manager.businessId]),rows=branches.rows.map(x=>({...x,revenue:num(x.revenue),orders:num(x.orders),aov:num(x.orders)?num(x.revenue)/num(x.orders):0})),avg=rows.length?rows.reduce((s,x)=>s+x.revenue,0)/rows.length:0;res.json({periodDays:28,branches:rows.map(x=>({...x,revenueVsBranchAveragePct:avg?((x.revenue-avg)/avg)*100:null})),branchAverageRevenue:avg})}catch(e){res.status(500).json({error:e.message||'Unable to benchmark branches'})}});
  app.get('/api/manager/intelligence/settings',manager,async(req,res)=>{const r=await pool.query(`select p.id product_id,p.name,p.price,coalesce(s.unit_cost,0) unit_cost,coalesce(s.stock_on_hand,0) stock_on_hand,coalesce(s.reorder_point,0) reorder_point,coalesce(s.lead_time_days,1) lead_time_days,coalesce(s.target_days,7) target_days from products p left join intelligence_product_settings s on s.product_id=p.id and s.business_id=p.business_id where p.business_id=$1 order by p.name`,[req.manager.businessId]);res.json(r.rows)});
  app.put('/api/manager/intelligence/settings/:productId',manager,async(req,res)=>{
    try{
      const product=await pool.query('select id from products where id=$1 and business_id=$2 limit 1',[req.params.productId,req.manager.businessId]);
      if(!product.rowCount)return res.status(404).json({error:'Menu product not found for this restaurant'});
      const r=await pool.query(`insert into intelligence_product_settings(business_id,product_id,unit_cost,stock_on_hand,reorder_point,lead_time_days,target_days) values($1,$2,$3,$4,$5,$6,$7) on conflict(business_id,product_id) do update set unit_cost=excluded.unit_cost,stock_on_hand=excluded.stock_on_hand,reorder_point=excluded.reorder_point,lead_time_days=excluded.lead_time_days,target_days=excluded.target_days,updated_at=now() returning *`,[req.manager.businessId,req.params.productId,num(req.body.unitCost),Math.max(0,num(req.body.stockOnHand)),Math.max(0,num(req.body.reorderPoint)),Math.max(.25,num(req.body.leadTimeDays)||1),Math.max(1,num(req.body.targetDays)||7)]);
      res.json(r.rows[0]);
    }catch(e){res.status(500).json({error:e.message||'Unable to update intelligence settings'});}
  });
  app.get('/api/manager/intelligence/branches',manager,async(req,res)=>{const r=await pool.query(`select * from restaurant_branches where business_id=$1 order by name`,[req.manager.businessId]);res.json(r.rows)});
  app.post('/api/manager/intelligence/branches',manager,async(req,res)=>{const r=await pool.query(`insert into restaurant_branches(business_id,name,code,address,latitude,longitude) values($1,$2,$3,$4,$5,$6) returning *`,[req.manager.businessId,clean(req.body.name,120),clean(req.body.code,30).toUpperCase(),clean(req.body.address,500)||null,req.body.latitude??null,req.body.longitude??null]);res.status(201).json(r.rows[0])});
}
export async function runIntelligenceSweep(pool){
  try{
    const businesses=await pool.query('select id from businesses');
    for(const b of businesses.rows){
      const r=await pool.query("select coalesce(sum(total) filter(where payment_status='PAID'),0)::numeric revenue,count(*)::int orders_count,count(*) filter(where status='DELIVERED')::int completed_orders from orders where business_id=$1 and created_at>=current_date and created_at<current_date+interval '1 day'",[b.id]);
      const x=r.rows[0];
      const aov=Number(x.orders_count)?Number(x.revenue)/Number(x.orders_count):0;
      await pool.query('insert into intelligence_snapshots(business_id,snapshot_date,revenue,orders_count,completed_orders,average_order_value) values($1,current_date,$2,$3,$4,$5) on conflict(business_id,snapshot_date) do update set revenue=excluded.revenue,orders_count=excluded.orders_count,completed_orders=excluded.completed_orders,average_order_value=excluded.average_order_value',[b.id,x.revenue,x.orders_count,x.completed_orders,aov]);
      const baseline=await pool.query("select avg(revenue)::numeric mean,coalesce(stddev_pop(revenue),0)::numeric sd from intelligence_snapshots where business_id=$1 and snapshot_date>=current_date-interval '28 days' and snapshot_date<current_date",[b.id]);
      const mean=Number(baseline.rows[0]?.mean||0),sd=Number(baseline.rows[0]?.sd||0),observed=Number(x.revenue||0),z=sd?Math.abs(observed-mean)/sd:0;
      if(sd&&z>=2){const severity=z>=3?'HIGH':'MEDIUM';await pool.query("insert into intelligence_anomalies(business_id,anomaly_type,severity,metric,observed_value,expected_value,explanation) select $1,'REVENUE',$2,'daily_revenue',$3,$4,$5 where not exists (select 1 from intelligence_anomalies where business_id=$1 and anomaly_type='REVENUE' and detected_at::date=current_date)",[b.id,severity,observed,mean,observed>mean?'Daily revenue is materially above the recent baseline.':'Daily revenue is materially below the recent baseline.'])}
    }
  }catch(error){console.error('Intelligence sweep warning:',error.message)}
}
