import crypto from 'node:crypto';
import {getBranding,DEFAULT_BRANDING} from './branding-engine.js';

const DEFAULT_RECEIPT_CONFIG={showLogo:true,logoPosition:'CENTER',showAddress:true,showPhone:true,showPayment:true,showDelivery:true,showOrderItems:true,paperWidth:'80MM',footerText:'Thank you for ordering with us.',headerText:'RECEIPT',accentColor:'',compact:false};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const configOf=c=>({...DEFAULT_RECEIPT_CONFIG,...(c&&typeof c==='object'?c:{})});
async function ensureReceipt(pool,orderId){const e=await pool.query('select * from receipts where order_id=$1',[orderId]);if(e.rowCount)return e.rows[0];const o=await pool.query('select id,order_number,total,payment_status from orders where id=$1',[orderId]);if(!o.rowCount)throw new Error('Order not found');if(String(o.rows[0].payment_status).toUpperCase()!=='PAID')throw new Error('A receipt is issued after payment is confirmed.');const token=crypto.randomBytes(32).toString('hex');const number=String(o.rows[0].order_number).replace(/[^A-Za-z0-9-]/g,'')+'-R';const r=await pool.query('insert into receipts(id,order_id,receipt_number,amount,receipt_access_token) values(gen_random_uuid(),$1,$2,$3,$4) on conflict(order_id) do update set receipt_access_token=coalesce(receipts.receipt_access_token,excluded.receipt_access_token) returning *',[orderId,number,o.rows[0].total,token]);return r.rows[0];}
async function getReceiptData(pool,orderId){const o=await pool.query('select o.*,c.name as customer_name,c.phone,c.email,b.name as business_name,b.pickup_address,b.mpesa_phone from orders o join customers c on c.id=o.customer_id join businesses b on b.id=o.business_id where o.id=$1',[orderId]);if(!o.rowCount)throw new Error('Order not found');const receipt=await ensureReceipt(pool,orderId);const [items,branding]=await Promise.all([pool.query('select product_name,quantity,unit_price,options from order_items where order_id=$1 order by id',[orderId]),getBranding(pool,o.rows[0].business_id)]);return {order:o.rows[0],items:items.rows,receipt,branding,config:configOf(branding.receipt_config)};}
function receiptMarkup(data){
  const o=data.order,r=data.receipt,b=data.branding,c=data.config||DEFAULT_RECEIPT_CONFIG;
  const primary=c.accentColor||b.primary_color||DEFAULT_BRANDING.primary_color;
  const width=c.paperWidth==='58MM'?'58mm':'80mm';
  const logo=c.showLogo&&b.logo_url?'<img class="logo" src="'+esc(b.logo_url)+'" alt="'+esc(b.display_name)+'">':'';
  const rows=c.showOrderItems?data.items.map(i=>'<tr><td>'+esc(i.product_name)+' × '+Number(i.quantity)+'</td><td>KSh '+(Number(i.unit_price)*Number(i.quantity)).toLocaleString('en-KE',{minimumFractionDigits:2})+'</td></tr>').join(''):'';
  const css=':root{--brand:'+esc(primary)+';--text:'+esc(b.text_color||'#172019')+';--paper:'+width+'}*{box-sizing:border-box}body{margin:0;background:#ecebe6;font-family:'+esc(b.font_family||DEFAULT_BRANDING.font_family)+';color:var(--text)}.receipt{width:var(--paper);max-width:100%;margin:20px auto;background:#fff;padding:18px 14px;box-shadow:0 10px 30px #0001}.head{text-align:'+(c.logoPosition==='LEFT'?'left':c.logoPosition==='RIGHT'?'right':'center')+';border-bottom:2px solid var(--brand);padding-bottom:12px;margin-bottom:12px}.logo{max-width:120px;max-height:60px;object-fit:contain;margin-bottom:7px}.name{font-size:18px;font-weight:900}.meta{font-size:10px;color:#6b726b;line-height:1.45}.title{font-size:10px;font-weight:900;letter-spacing:.14em;color:var(--brand);margin-top:7px}.rows{width:100%;border-collapse:collapse;font-size:10px}.rows td{padding:6px 0;border-bottom:1px dashed #ddd}.rows td:last-child{text-align:right}.details{font-size:10px;display:grid;gap:3px;margin-top:10px}.total{display:flex;justify-content:space-between;border-top:2px solid var(--brand);margin-top:10px;padding-top:10px;font-weight:900}.foot{text-align:center;border-top:1px solid #ddd;margin-top:14px;padding-top:10px;font-size:10px;color:#6b726b}.print{display:block;margin:12px auto;border:0;background:var(--brand);color:#fff;padding:10px 14px;font-weight:900}@media print{body{background:#fff}.receipt{box-shadow:none;margin:0 auto;padding:8px}.print{display:none}}';
  const head='<header class="head">'+logo+'<div class="name">'+esc(b.display_name||o.business_name)+'</div><div class="title">'+esc(c.headerText)+'</div>'+(c.showAddress&&o.pickup_address?'<div class="meta">'+esc(o.pickup_address)+'</div>':'')+(c.showPhone&&b.mpesa_phone?'<div class="meta">'+esc(b.mpesa_phone)+'</div>':'')+'</header>';
  const details='<div class="details"><div><b>Receipt:</b> '+esc(r.receipt_number)+'</div><div><b>Order:</b> '+esc(o.order_number)+'</div><div><b>Date:</b> '+esc(new Date(r.issued_at).toLocaleString('en-KE'))+'</div>'+(c.showPayment?'<div><b>Payment:</b> '+esc(o.payment_method||'PAID')+'</div>':'')+(c.showDelivery?'<div><b>Delivery:</b> KSh '+Number(o.delivery_fee||0).toLocaleString('en-KE',{minimumFractionDigits:2})+'</div>':'')+'</div>';
  return '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(b.display_name)+' Receipt</title><style>'+css+'</style></head><body><article class="receipt">'+head+'<table class="rows">'+rows+'</table>'+details+'<div class="total"><span>Total</span><span>KSh '+Number(o.total||0).toLocaleString('en-KE',{minimumFractionDigits:2})+'</span></div><footer class="foot">'+esc(c.footerText)+'</footer></article><button class="print" onclick="print()">PRINT RECEIPT</button></body></html>';
}
export function registerReceiptEngine(app,pool,{requireManager}){
app.get('/api/manager/receipts/:orderId',requireManager,async(req,res)=>{try{const data=await getReceiptData(pool,String(req.params.orderId));if(String(data.order.business_id)!==String(req.manager.business_id))return res.status(403).json({error:'You can only access receipts for your restaurant'});res.json({receipt:data.receipt,order:data.order,items:data.items,branding:data.branding,config:data.config,html:receiptMarkup(data)});}catch(e){res.status(400).json({error:e.message||'Unable to load receipt'});}});
app.get('/api/receipts/public/:token',async(req,res)=>{try{const x=await pool.query('select order_id from receipts where receipt_access_token=$1',[String(req.params.token)]);if(!x.rowCount)return res.status(404).json({error:'Receipt not found'});const data=await getReceiptData(pool,x.rows[0].order_id);res.json({receipt:data.receipt,order:data.order,items:data.items,branding:data.branding,config:data.config});}catch(e){res.status(404).json({error:e.message||'Receipt not found'});}});
app.get('/api/receipts/public/:token/html',async(req,res)=>{try{const x=await pool.query('select order_id from receipts where receipt_access_token=$1',[String(req.params.token)]);if(!x.rowCount)return res.status(404).send('Receipt not found');const data=await getReceiptData(pool,x.rows[0].order_id);res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','no-store');res.send(receiptMarkup(data));}catch(e){res.status(404).send('Receipt not found');}});
app.get('/api/manager/receipt-settings',requireManager,async(req,res)=>{try{const b=await getBranding(pool,req.manager.business_id);res.json({config:configOf(b?.receipt_config)});}catch(e){res.status(500).json({error:e.message||'Unable to load receipt settings'});}});
app.patch('/api/manager/receipt-settings',requireManager,async(req,res)=>{try{const cfg=configOf(req.body);const current=await getBranding(pool,req.manager.business_id);await pool.query('insert into restaurant_branding(business_id,display_name,receipt_config,updated_at) values($1,$2,$3,now()) on conflict(business_id) do update set receipt_config=excluded.receipt_config,updated_at=now()',[req.manager.business_id,current.name||current.display_name||'',JSON.stringify(cfg)]);res.json({config:cfg});}catch(e){res.status(400).json({error:e.message||'Unable to save receipt settings'});}});
export {DEFAULT_RECEIPT_CONFIG,configOf,ensureReceipt,getReceiptData,receiptMarkup};